import * as fs from 'fs';
import * as path from 'path';

import { Rule } from '../types';

/**
 * Reads the rule data generated by `scripts/prebuild`. Server-only: used from
 * `getStaticPaths` / `getStaticProps`, so Next strips it from the client bundle.
 *
 * Resolved from `process.cwd()` rather than `__dirname`. The previous code used
 * `path.join(__dirname, '../../../../src/data/rules/')`, which depended on where
 * Next happened to emit the server chunk for this page -- a path that would
 * break silently on a Next upgrade with no compile error.
 */
const RULES_DIR = path.join(process.cwd(), 'src', 'data', 'rules');

export function listRuleIds(): string[] {
  return fs.readdirSync(RULES_DIR).map(file => path.parse(file).name);
}

export function readRule(id: string): Rule {
  return JSON.parse(
    fs.readFileSync(path.join(RULES_DIR, `${id}.json`), 'utf8')
  );
}
