[metadata]
creation_date = "2023/09/04"
integration = ["endpoint"]
maturity = "production"
updated_date = "2025/09/16"

[rule]
author = ["Elastic"]
description = "Identifies a suspicious network connection."
from = "now-9m"
index = ["logs-endpoint.events.network-*"]
language = "eql"
license = "Elastic License v2"
name = "Suspicious Network Connection"
risk_score = 47
rule_id = "11111111-2222-3333-4444-555555555555"
severity = "medium"
type = "eql"
query = "network where event.type == \"start\""
tags = [
  "Domain: Endpoint",
  "OS: Linux",
  "Use Case: Threat Detection",
  "Resources: Investigation Guide",
]
